name: Build N64 Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile ROM using Libdragon
        run: |
          docker run --rm -v "$(pwd):/n64" -w /n64 ghcr.io/libdragon/libdragon make

      - name: Store Compiled Z64 ROM
        uses: actions/upload-artifact@v4
        with:
          name: N64-ROM-Artifact
          path: deadbeat_demo.z64
